### ISSUE TITLE
working repeatable windows 10 pro docker container install instructions

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#14]
this involves a couple things:
- investigating why the current docker setup doesn't work well on win 10
- create an emkc.bat version of emkc for windows users

**Comment by Pyroseza** [comment]
The main issue I have found is that when you bind a port and shut down a container, the Docker service does not clean up the ports properly and leaves them bound. So if you had to start up the Docker instance then it won’t be able to access those ports again. 

There have been several issues logged with Docker support here on Github and don’t seem to be fixing it anytime soon. There idea of a solution it to keep restarting the Docker service which does not work all the time for me.

**Comment by realtux** [comment]
you closed this out, is there a solution committed or written up that you forgot to push?

**Comment by Pyroseza** [comment]
I closed it because currently there are issues with Docker on Windows, I’ll link the issues for them. I reckon once they’ve sorted it out then the docker instances should work fine.

**Comment by Pyroseza** [comment]
Main issues page: https://github.com/docker/for-win/issues

Closed issues, Docker support blaming the problem on Windows and not fixing it on there side:

https://github.com/docker/for-win/issues/204

https://github.com/docker/for-win/issues/458
