### ISSUE TITLE
emkc challenges format

### ISSUE THREAD

**Issue by Nova-Ardent** [engineer-man/emkc#16]
Format: 

{challenge name}
Challenge : {id}
 Difficulty: {dif}/5  

{description}

  {example input}
 {example output}

Example:

Ascending values 
Challenge: 1 
Difficulty: 1/5

  Given an CSV of numbers, write a program that can determine if all of these values are in ascending order. That is they’re ordered from lowest to highest values. Return a boolean stating whether or not the numbers are in order. You may assume that the input will always be valid, but may not assume that there will be a fixed set of numbers. 

For: 1, 2, 2, 4, 9 
output: true

  for: 1, 3, 2, 7, 12
 output: false

**Comment by realtux** [comment]
obsolete
