### ISSUE TITLE
view previous snippets a user created

### ISSUE THREAD

**Issue by Nova-Ardent** [engineer-man/emkc#18]
make it so it can identify html code (possibly by the header <!DOCTYPE html>) and display its contents on a new screen.

**Comment by kalix123** [comment]
1. When you click snippets in the menu, don't make a new snippet right away. land on a page where you can change the name, what language it is in,.
2. ability to see what snippets you have created

**Comment by tipztek** [comment]
for 1) that was only code rooms that did that. for 2) i agree, coming soon

**Comment by realtux** [comment]
closing in favor of #29
