### ISSUE TITLE
EM history page

### ISSUE THREAD

**Issue by Nova-Ardent** [engineer-man/emkc#19]
Shows all updates to emkc and the history behind it like so. (I'm obviously missing a few dates, like emkc was born etc..)
May 13, 2017
Engineer man posted his first video

June 10, 2017
Engineer man had his first being channel explosion

July 29, 2018
Engineer man posted his first 1 million viewed video.

August 3, 2018
The discord was created

August 28th, 2018
Armageddon happened

August 28th, 2018
Security was increased to prevent armageddon 2

September 20th, 2018
Felix run was born, and coding was allowed to be done as a function of the discord server.

**Comment by realtux** [comment]
subscriber milestones:
5/13/2017 - 1 subscriber
6/22/2017 - 100 subscribers
7/28/2017 - 500 subscribers
11/10/2017 - 1,000 subscribers
6/14/2017 - 5,000 subscribers
7/22/2018 - 10,000 subscribers
8/9/2018 - 25,000 subscribers
8/23/2018 - 50,000 subscribers
