### ISSUE TITLE
create 10 easy challenges

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#20]
**official list for this iteration**
- [x] reverse a string
- [x] in a string of numbers, determine which has the highest frequency
- [x] sum a comma separated list of numbers
- [x] given a fibonacci sequence number, calculate the next n digits
- [x] given two comma separated lists of numbers, determine the overlapping numbers

**how to create a challenge:**
1. create a new record in challenges table
2. create a new folder in platform/resources/challenges in the format of [pk of new record in db]_[simple name you select]. ex. `1_reverse_string` or `2_number_frequency`.
3. in that folder create an abstract.html to describe the challenge
4. also in that folder, create a tests.json to describe the test cases

see the two that are already made for an example.

**Comment by kalix123** [comment]
1. reverse a string
2. iterate over a list in reverse
3. count down from 10
4. write a basic calculator that can do * / + -
5. write a function that returns the longest word in a list
6. implement a basic sorting algorithm
7. write a function that calculates the first 100 Fibonacci numbers
8. write a function that computes the sum of a list
9. write a function to combine two lists
10. write a function that tells you all the items in even positions in a list

**Comment by kalix123** [comment]
Return true if a given fraction in the form “a/b” is equal to say 2/3
Meaning that if the fraction Is equal to 4/6 return true. Or anything for that matter.
(2/3 is just an example.)
