### ISSUE TITLE
create 10 medium challenges

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#21]

**Comment by kalix123** [comment]
1. write a program that can generate semi correct sentences (example. give it a list of verbs, nouns, etc... and tell it in which order these words should be placed)
2. write a program that converts English to binary
3. write a program that tells you what language inputted text is in
4. write a program that converts an input to numbers (as in assign each letter a value) (IMPORTANT: not allowed to use a dictionary. can't say that {'a': 1})
5. Write a program which will find all numbers which are divisible by 7 but are not a multiple of 5 between 500 and 2000
6. find what percent of word 1 matches word 2. example. "some" and "stone" only the first letter. but with a larger word It would get harder.
7. write a program that calculates the number of letters and digits in an input. example: "hello23" 6 letters and 2 digits
8. Calculate pi using the Monte Carlo Method
that's all I can think of for now. I'll add some more later.

**Comment by konidev20** [comment]
9. Write a program to take in a Roman Numeral (eg. XI) and print the corresponding Roman Numeral name (eg. XI - eleven, XII - twelve etc.). Accept Roman Numerals between 1 & 10000.

**Comment by sggts04** [comment]
While making a website, you were tasked to validate user passwords. Your job today is to write a code that will return whether the entered password is a valid one or not. 
The conditions to check the validity of a password are: 
The Password should be 6 to 20 character long.
It should contain at least one uppercase letter(A-Z).
It shoud have at least one lowercase letter(a-z) .
It should have atleast one numerical character(0-9).

**Comment by Nova-Ardent** [comment]
(Hard) Write a program to generate the calculated output of a strings in prefix, postfix, and infix form. The strings may contain, addition, subtraction, multiplication, division and carets (exponents)
Example for input
+ 1 6
1 8 + 
1 + 3

Output:
7
9
4

**Comment by brtwrst** [comment]
validate credit card numbers
https://www.fivecentnickel.com/how-do-you-know-if-a-credit-card-number-is-valid/

**Comment by kalix123** [comment]
Return true if a given fraction in the form “a/b” is equal to say 2/3
Meaning that if the fraction Is equal to 4/6 return true. Or anything for that matter.
(2/3 is just an example.)
