### ISSUE TITLE
Bug with the questions page - Link to user @undefined

### ISSUE THREAD

**Issue by Coach97** [engineer-man/emkc#37]
On the questions page, the URL to the author's profile leads to https://emkc.org/@undefined instead of the user's profile.
![image](https://user-images.githubusercontent.com/14850649/48823866-4aa58080-ed5a-11e8-881c-37fe087666e8.png)

**Comment by DBragz** [comment]
resolved in ab7329e61503a9f183fc24f4bce81065fc0444cc
