### ISSUE TITLE
Update Video Request rank immediantly when you upvote it.

### ISSUE THREAD

**Issue by derekwilling** [engineer-man/emkc#45]
You have to refresh the page to see the updated score. Can this be fixed so that the score is automatically updated for the viewer when the request is upvoted?

![peek 2018-12-29 00-23](https://user-images.githubusercontent.com/33207400/50533806-19aa2f80-0b00-11e9-8bd2-d04fa9f1ec8e.gif)

**Comment by Pyroseza** [comment]
Yep this can definitely be fixed

**Comment by realtux** [comment]
no longer a feature
