### ISSUE TITLE
investigate long compilation for swift code

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#49]
investigate compatibility with lxc

**Comment by Kyle-Undefined** [comment]
Here is a piece of code that causes it to error out with `xargs: timeout: terminated by signal 9`. What I have noticed is that it seems to on first run, after awhile of no tests. After the initial run, no challenge gives an issue. The only language I encountered that behaved this way.

```
var value1 = CommandLine.arguments[1]

// write your solution here
let reversed = String(value1.reversed())
print(reversed)
```

**Comment by Kyle-Undefined** [comment]
After some testing, it appears this isn't an issue anymore. I can't get the Swift compiler to error out no matter how long I wait. Should be ok to close, might be due to the migration that just occurred.
