### ISSUE TITLE
investigate possible use of str -> array for certain challenge languages

### ISSUE THREAD

**Issue by realtux** [engineer-man/emkc#50]
js accepts things like a = [1,2,3], as does ruby, php, and others

java, c, c++, not so much and it makes the challenges unfair. investigate maybe handling that logic as part of the challenge init

**Comment by kalix123** [comment]
Which challenges? some of the challenges you are supposed to print out a , separated list.

**Comment by Nova-Ardent** [comment]
I dont see how this makes challenges unfair, its a legitimate downfall of those languages that must be overcome when using them in development.

**Comment by realtux** [comment]
closing because nobody is complaining
