### ISSUE TITLE
Make more challenges

### ISSUE THREAD

**Issue by kalix123** [engineer-man/emkc#53]
So we need more challenges for emkc.
It's not that difficult to make a challenge.
You can clone the repo and look at the other challenges or follow the steps below.

**how to create a challenge:**

1. create a new record in challenges table
2. create a new folder in platform/resources/challenges in the format of [pk of new record in db]_[simple name you select]. ex. `1_reverse_string` or `2_number_frequency`.
3. in that folder create an abstract.html to describe the challenge
4. also in that folder, create a tests.json to describe the test cases

**Comment by SirDagen** [comment]
Sorry, I dont get it: "create a new record in challenges table"

**Comment by derekwilling** [comment]
Is there a specific way to create a new record in the challenges table? I see the sql insert statements in the `/platform/migrations/migrations` folder. Are we supposed to manually add a file there and run `./emkc migrate` to complete step 1?
