### ISSUE TITLE
Add pop-up notification on challenge solve

### ISSUE THREAD

**Issue by soruh** [engineer-man/emkc#54]
I think a notification, once you solve a challenge would be nice.

The way it is now only the little status indicators on the top left and in the "console" change
which can be easily missed and just doesn't feel as rewarding as a proper notification.

The popup would probably have to be triggered somewhere around [here](https://github.com/engineer-man/emkc/blob/develop/platform/resources/jsx/challenge.jsx#L48), but I don't feel sufficiently confident with react and how it is utilized here to write this myself.

**Comment by realtux** [comment]
maybe this just happens once an initial solve happens
