### ISSUE TITLE
implement proper 404 page

### ISSUE THREAD

**Issue by brootware** [engineer-man/emkc#7]
as the name suggests it seems most of the pages aren't accessible. Screenshot below.
<img width="1470" alt="screen shot 2018-09-13 at 9 29 11 am" src="https://user-images.githubusercontent.com/7734956/45461836-b0acd080-b737-11e8-9727-37d833ae0c5c.png">

**Comment by realtux** [comment]
pages don't exist, need to replace with 404 page

**Comment by realtux** [comment]
implemented in latest
