### ISSUE TITLE
Allow users to edit/delete their own snippets

### ISSUE THREAD

**Issue by dheiberg** [engineer-man/emkc#74]
Since snippets can be attached to a user's account, it would be nice if they were able to edit their own snippets, or even delete them. I'm thinking this would look like having an 'Edit' button above the snippet that validates you are indeed the snippet owner, and a 'Save' button that comes up afterwards. 

If this were to be implemented, having a version history would also be a good idea so that people can refer to a previous version if need be.

**Comment by Brikaa** [comment]
We can close this. Only the version history wasn't implemented but I don't think that would be a problem for now.
