### ISSUE TITLE
EMKC challenge solved with incorrect code

### ISSUE THREAD

**Issue by dheiberg** [engineer-man/emkc#75]
The challenges can be marked as solved even if the solution doesn't work for all test cases. This seems to be because the solution is only run against a subset of tests, and if it passes those then the tests are passed. 

Example:
https://emkc.org/challenges/13/python
```py
print(max(value1, key=lambda x: value1.count(x)))
```

This solution works for cases where there is only a single letter that occurs most often, but fails for cases with multiple equally occuring letters. However if this is run against test cases that only test with a single max occuring letter, the challenge is solved, despite the solution being flawed and failing other cases.

**Comment by realtux** [comment]
probably will fix this with official cases, eventually. it's a known issue though
